version: '3.1'

services:
  db:
    image: percona:latest
    volumes:
      # Place mysql dump in mysql folder for automatic import
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nativegb
      MYSQL_USER: nativegb
      MYSQL_PASSWORD: nativegb
      MYSQL_DATABASE: nativegb
