# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.name = "magento2"
  end


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 8001
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provider :virtualbox do |vb|
            vb.customize ['modifyvm', :id,'--memory', '2048']
        end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.16"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/var/www/", type: "nfs"

  config.vm.provision "shell", type: "shell", path: "provision.sh"
  config.vm.provision "mysql", type: "shell", path: "provision-mysql.sh"
end
